### ISSUE TITLE
Get time interval from trajectory files

### ISSUE THREAD

**Issue by jchodera** [choderalab/msm-pipeline#21]
Not all of our projects use the same time interval of 0.25 ns per frame.

[This line](https://github.com/choderalab/msm-pipeline/blob/master/msmpipeline/msmpipeline.py#L153), and possibly others, hard-code this assumption.

We should instead get the time interval between frames from the trajectories.

**Comment by maxentile** [comment]
Addressed here: https://github.com/choderalab/msm-pipeline/pull/24

**Comment by maxentile** [comment]
Can I close this?

**Comment by jchodera** [comment]
Yes, thanks!
